server:
  servlet:
    context-path: /api
    session:
      timeout: PT60M

spring:
  mvc:
    favicon:
      enable: false
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easybbs?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

admin:
  account: admin
  password: admin123
  emails: test@qq.com

project:
  folder: E:/Desktop/web_hw/backend

log:
  root:
    level: debug

inner:
  api:
    appKey: easybbs
    appSecret: easybbs_key

web:
  api:
    url: http://localhost:7070/api/innerApi/refresSysSetting


isDev: true

logging:
  config: classpath:logback-spring.xml

